# Generated by Django 2.2.2 on 2019-06-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='Enter a brief description of the book', max_length=500)),
                ('url', models.URLField(blank=True, max_length=300)),
                ('author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Author')),
                ('category', models.ManyToManyField(to='core.Category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
