# Generated by Django 2.2.2 on 2019-06-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190626_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='times_favorited',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
