# Generated by Django 2.2.2 on 2019-06-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190628_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='core.Book'),
        ),
    ]
